name: "runs-on: freebsd-latest"
description: "💻 Emulate 'runs-on: freebsd-latest' for GitHub Actions"
author: Jacob Hummer <jcbhmr@outlook.com>
branding:
  icon: terminal
  color: green
inputs:
  "Use the reusable workflow instead!":
    description: https://github.com/runs-on/freebsd#readme
runs:
  using: composite
  steps:
    - shell: bash
      run: echo 'https://github.com/runs-on/freebsd#readme'; exit 1
