name: Hello world 123 #runs-on: freebsd-latest
description: Description # 💻 Emulate 'runs-on: freebsd-latest' for GitHub Actions
author: Jacob Hummer <jcbhmr@outlook.com>
branding:
  icon: terminal
  color: green
runs:
  using: composite
  steps:
    - shell: bash
      # prettier-ignore
      run: echo Hello world! # echo '::error::You need to use the reusable workflow! Check out the website for a short getting started guide. https://jcbhmr.github.io/runs-on-freebsd-latest/' && exit 1
