on:
  workflow_call:
    inputs:
      name:
        type: string
      permissions:
        type: string
      needs:
        type: string
      if:
        type: string
      runs-on:
        type: string
      environmment:
        type: string
      concurrency:
        type: string
      outputs:
        type: string
      env:
        type: string
      defaults:
        type: string
      steps:
        type: string
        required: true
      timeout-minutes:
        type: string
      strategy:
        type: string
      continue-on-error:
        type: string
      container:
        type: string
      services:
        type: string
      uses:
        type: string
      with:
        type: string
      secrets:
        type: string
jobs:
  freebsd:
    runs-on: macos-12
    steps:
      # - uses: runs-on/freebsd@v0.1.0
      #   with: ${{ inputs }}
      - uses: actions/checkout@v3
      - uses: ./
        with: ${{ inputs }}
